# Text Cleaning

## Lowercasing

In [1]:
import pandas as pd

In [2]:
d=pd.read_csv('train_data_cleaning.csv')

In [3]:
d.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this # earthquake...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask . Canada,1
2,5,NaN,NaN,All residents asked to ' shelter in place ' ...,1
3,6,NaN,NaN,"13,000 people receive # wildfires evacuation ...",1
4,7,NaN,NaN,Just got sent this photo from Ruby # Alaska a...,1

In [4]:
d['text'][0]

'Our Deeds are the Reason of this  # earthquake May ALLAH Forgive us all'

In [5]:
d['text'].str.lower()[0]

'our deeds are the reason of this  # earthquake may allah forgive us all'

In [6]:
text="<h1>Hello World</h1>"

In [7]:
import re

In [8]:
re.sub(r'<.*?>', '', text)
## r means it is a raw string, <.*?> means any character between < and >, ? means non-greedy match, '' means replace with empty string

'Hello World'

In [9]:
data=pd.DataFrame({"col":["<h1>Hello World</h1>","<a>Google</a>","<p>This is a paragraph.</p>"]})

In [10]:
data

                           col
0         <h1>Hello World</h1>
1                <a>Google</a>
2  <p>This is a paragraph.</p>

In [11]:
def html_cleaning(text):
    empty_html = []
    for i in text:
        clean_text = re.sub(r'<.*?>', '', i)
        empty_html.append(clean_text)
    return empty_html

In [12]:
data.apply(html_cleaning)

                    col
0           Hello World
1                Google
2  This is a paragraph.

In [13]:
text="Hey https://www.google.com, how are you"

In [14]:
re.sub(r'https?://\S+|www\.\S+', '', text)

'Hey  how are you'

In [15]:
text="hey, I am Amit ! How are you?"

In [16]:
re.sub(r"[^\w\s]","",text)

'hey I am Amit  How are you'

In [17]:
slang_dict = {"asap": "as soon as possible", "gn": "good night", "lol": "laugh out loud", "yolo": "you only live once"}

In [ ]:
slang=pd.DataFrame({"slang":["Hey call me asap","hey hello gn","lol that was funny","hey yolo, you know it"]})

                   slang
0       Hey call me asap
1           hey hello gn
2     lol that was funny
3  hey yolo, you know it

In [26]:
text="Hey call me asap"

In [27]:
def expand_slang(text,slang_dict):
    words=text.split()
    return " ".join([slang_dict.get(word,word) for word in words])

In [28]:
expand_slang(text,slang_dict)

'Hey call me as soon as possible'

In [30]:
%pip install textblob

Collecting textblob
  Downloading textblob-0.20.1-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: nltk>=3.9 in e:\GenAI\python\venv\Lib\site-packages (from textblob) (3.10.0)
Requirement already satisfied: defusedxml in e:\GenAI\python\venv\Lib\site-packages (from nltk>=3.9->textblob) (0.7.1)
Requirement already satisfied: click in e:\GenAI\python\venv\Lib\site-packages (from nltk>=3.9->textblob) (8.3.2)
Requirement already satisfied: joblib in e:\GenAI\python\venv\Lib\site-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in e:\GenAI\python\venv\Lib\site-packages (from nltk>=3.9->textblob) (2026.7.10)
Requirement already satisfied: tqdm in e:\GenAI\python\venv\Lib\site-packages (from nltk>=3.9->textblob) (4.68.4)
Requirement already satisfied: colorama in e:\GenAI\python\venv\Lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Downloading textblob-0.20.1-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   ---------------------------------------- 625.0/625.0 kB 4.7 MB/s  0:00:00
Installing collected packages: textblob
Successfully installed textblob-0.20.1
Note: you may need to restart the kernel to use updated packages.

In [29]:
text="Hey how ar you, i ws searchi for you yestrday and i couuldnt findd yoou !"

In [31]:
from textblob import TextBlob

In [32]:
texblb = TextBlob(text)

In [35]:
text="Hi i ws lokin fr you"

In [37]:
texblb = TextBlob(text)

In [38]:
texblb.correct().string

'I i was loin fr you'

In [45]:
from nltk.corpus import stopwords

In [49]:
english=stopwords.words('english')

In [53]:
text="Hey how are you i am fine i was looking for you"

In [55]:
without_stops=[]
for i in text.split():
    if i in english:
        without_stops.append("")
    else:
        without_stops.append(i)
    x=without_stops[:]

In [56]:
without_stops

['Hey', '', '', '', '', '', 'fine', '', '', 'looking', '', '']

In [57]:
## Removing emoji --> spam detection / topic modelling

In [58]:
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [59]:
data={
    'content':[
        "I love pizza 🍕 so much!",
        "Good morning! ☀️",
        "Let's go for a ride 🚗",
        "Vacation time 🏖️",
        "Happy birthday! 🎉",
        "Feeling strong 💪"
    ]
}

data = pd.DataFrame(data)

In [61]:
data

                   content
0  I love pizza 🍕 so much!
1         Good morning! ☀️
2    Let's go for a ride 🚗
3         Vacation time 🏖️
4        Happy birthday! 🎉
5         Feeling strong 💪

In [62]:
data['content'].apply(remove_emoji)

0    I love pizza  so much!
1            Good morning!
2      Let's go for a ride
3            Vacation time
4          Happy birthday!
5           Feeling strong
Name: content, dtype: str

In [63]:
%pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ---------------------------------------- 0.0/608.4 kB ? eta -:--:--
   ---------------------------------------- 608.4/608.4 kB 5.6 MB/s  0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0
Note: you may need to restart the kernel to use updated packages.

In [64]:
import emoji

In [65]:
def emoji_to_text(text):
    return emoji.demojize(text, delimiters=(" ", " "))

In [66]:
text = "I love pizza 🍕 so much! Good morning! ☀️ Let's go for a ride 🚗 Vacation time 🏖️ Happy birthday! 🎉 Feeling strong 💪"

In [67]:
emoji_to_text(text)

"I love pizza  pizza  so much! Good morning!  sun  Let's go for a ride  automobile  Vacation time  beach_with_umbrella  Happy birthday!  party_popper  Feeling strong  flexed_biceps "