# Text Cleaning

## Lowercasing

In [1]:
import pandas as pd

In [2]:
d=pd.read_csv('train_data_cleaning.csv')

In [3]:
d.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this # earthquake...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask . Canada,1
2,5,NaN,NaN,All residents asked to ' shelter in place ' ...,1
3,6,NaN,NaN,"13,000 people receive # wildfires evacuation ...",1
4,7,NaN,NaN,Just got sent this photo from Ruby # Alaska a...,1

In [4]:
d['text'][0]

'Our Deeds are the Reason of this  # earthquake May ALLAH Forgive us all'

In [5]:
d['text'].str.lower()[0]

'our deeds are the reason of this  # earthquake may allah forgive us all'

In [6]:
text="<h1>Hello World</h1>"

In [7]:
import re

In [8]:
re.sub(r'<.*?>', '', text)
## r means it is a raw string, <.*?> means any character between < and >, ? means non-greedy match, '' means replace with empty string

'Hello World'

In [9]:
data=pd.DataFrame({"col":["<h1>Hello World</h1>","<a>Google</a>","<p>This is a paragraph.</p>"]})

In [10]:
data

                           col
0         <h1>Hello World</h1>
1                <a>Google</a>
2  <p>This is a paragraph.</p>

In [11]:
def html_cleaning(text):
    empty_html = []
    for i in text:
        clean_text = re.sub(r'<.*?>', '', i)
        empty_html.append(clean_text)
    return empty_html

In [12]:
data.apply(html_cleaning)

                    col
0           Hello World
1                Google
2  This is a paragraph.

In [13]:
text="Hey https://www.google.com, how are you"

In [14]:
re.sub(r'https?://\S+|www\.\S+', '', text)

'Hey  how are you'

In [15]:
text="hey, I am Amit ! How are you?"

In [16]:
re.sub(r"[^\w\s]","",text)

'hey I am Amit  How are you'

In [17]:
slang_dict = {"asap": "as soon as possible", "gn": "good night", "lol": "laugh out loud", "yolo": "you only live once"}

In [ ]:
slang=pd.DataFrame({"slang":["Hey call me asap","hey hello gn","lol that was funny","hey yolo, you know it"]})

                   slang
0       Hey call me asap
1           hey hello gn
2     lol that was funny
3  hey yolo, you know it

In [26]:
text="Hey call me asap"

In [27]:
def expand_slang(text,slang_dict):
    words=text.split()
    return " ".join([slang_dict.get(word,word) for word in words])

In [28]:
expand_slang(text,slang_dict)

'Hey call me as soon as possible'