## Data gathering from JSON Data

In [11]:
import pandas as pd

In [12]:
pd.read_json('iris.json')

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [13]:
pd.read_json('https://jsonplaceholder.typicode.com/posts')

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

### Gathering sql data and then need to apply some analysis of want to build model on it --->
### mysql.connector
### function which can help us with connecting to our database ---> connect()
### connect() ---> host ---> server ---> localhost,
### connect() ---> user --->username
### connect() ---> password
### connect() ---> database --->database name

### read_sql_query() --->'sql query', database connection variable

In [14]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in e:\GenAI\python\venv\Lib\site-packages (9.7.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
import mysql.connector

In [16]:
data=mysql.connector.connect(host='localhost', user='root', password='', database='world')

In [18]:
df=pd.read_sql_query('SELECT * FROM city', con=data)

C:\Users\Asus\AppData\Local\Temp\ipykernel_17080\2427363076.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query('SELECT * FROM city', con=data)

In [19]:
df

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [20]:
pd.read_sql_query('SELECT * FROM city where Population > 1000000', con=data)

C:\Users\Asus\AppData\Local\Temp\ipykernel_17080\1281906203.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('SELECT * FROM city where Population > 1000000', con=data)

       ID          Name CountryCode          District  Population
0       1         Kabul         AFG             Kabol     1780000
1      35         Alger         DZA             Alger     2168000
2      56        Luanda         AGO            Luanda     2022000
3      69  Buenos Aires         ARG  Distrito Federal     2982146
4      70    La Matanza         ARG      Buenos Aires     1266461
..    ...           ...         ...               ...         ...
232  3798       Phoenix         USA           Arizona     1321045
233  3799     San Diego         USA        California     1223400
234  3800        Dallas         USA             Texas     1188580
235  3801   San Antonio         USA             Texas     1144646
236  4068        Harare         ZWE            Harare     1410000

[237 rows x 5 columns]